"""initial

Revision ID: 9eebb6bcc886
Revises: 
Create Date: 2024-04-19 15:26:29.216505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9eebb6bcc886'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('name', sa.String(length=32), nullable=False),
                    sa.Column('pre_subscription', sa.Boolean(),
                              nullable=False),
                    sa.Column('gpt3_requests', sa.Integer(), nullable=False),
                    sa.Column('gpt4_requests', sa.Integer(), nullable=False),
                    sa.Column('image_requests', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
